apiVersion: skaffold/v1
kind: Config
profiles:
  - name: local
    build:
      artifacts:
        - image: lift/accessing-data-mysql
          jib:
            type: maven
            args:
              - -Plocal
#          buildpack:
#            builder: "cloudfoundry/cnb:cflinuxfs3"
      tagPolicy:
        sha256: {}
      local:
        push: false
    deploy:
      kubectl:
        manifests:
          - deployments/kubernetes/local/manifest.yaml
#
# Will be using k8s yaml files for services
#
  - name: local-services
    deploy:
      kubectl:
        manifests:
          - deployments/kubernetes/local-services/**/manifest.yaml